site_name: Aans Portfolio
site_url: https://laansdole.github.io/LaansDole/
site_author: Do Le Long An
site_description: My README Profile on GitHub
repo_url: https://github.com/LaansDole/LaansDole

nav:
  - My Skills <i class="fa-solid fa-address-card"></i>: index.md 
  - Daily DevOps <i class="fa-solid fa-gears"></i>: daily-devops.md
  - Terminal Portfolio <i class="fa-solid fa-terminal"></i>: cli.md

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  favicon: images/favicon.ico
  logo: images/aans-logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

extra_css:
  - style/index/index.css
  - style/cli/cli.css
  - style/bootstrap/_containers.css
  - style/bootstrap/_containers.css.map
  - style/bootstrap/_buttons.css
  - style/bootstrap/custom-bootstrap.css

extra_javascript:
  - script/cli/settings.js
  - script/cli/main-cli.js
  - script/cli/resize-host.js
  - script/index.js

plugins:
  - search
  - blog
  - extra-sass
