site_name: Aans Dev Portfolio
site_url: https://laansdole.github.io/LaansDole/
site_author: you
site_description: My README Profile on GitHub

nav:
  - About: index.md

theme:
  name: mkdocs
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - yaml
