site_name: Aans Dev Portfolio
site_url: https://laansdole.github.io/LaansDole/
site_author: Do Le Long An
site_description: My README Profile on GitHub
repo_url: https://github.com/LaansDole/LaansDole

nav:
  - Introduction: index.md

theme:
  name: mkdocs
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - yaml

docs_dir: docs

extra_css:
  - css/main.css

extra_javascript:
  - script/main.js
