# This is a basic workflow to help you get started with Actions

name: generate-daily-joke
run-name: Generating Daily Joke

# Controls when the workflow will run
on:
  push:
    paths:
      - "**.js"
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-edit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DAILY_JOKES }}
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm install
      - name: Edit markdown
        run: |
          npm start
          npm run build
      - name: Commit markdown
        run: |
          git config --global user.name 'LaansDole'
          git config --global user.email 'LaansDole@users.noreply.github.com'
          git commit -am "Generated Daily Joke"
          git pull
          git push --force
