name: deploy-gh-page

on:
  push:
    paths:
      - "docs/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DAILY_JOKES }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build
        run: mkdocs build

      - name: Add, commit, and push site directory
        run: |
          git config --global user.email "LaansDole@users.noreply.github.com"
          git config --global user.name "LaansDole"
          git clone -b gh-pages "https://${{ secrets.DAILY_JOKES }}@github.com/${{ github.repository }}" temp
          cp -r site/* temp/
          cd temp
          git add .
          git commit -m "Update site"
          git push "https://${{ secrets.DAILY_JOKES }}@github.com/${{ github.repository }}" gh-pages
